### GET /api/cursos recupera todos los directores
GET http://localhost:3000/api/cursos

### GET /api/cursos/:id recupera un plataforma
GET http://localhost:3000/api/cursos/1

### GET /api/cursos/:id recupera un plataforma - NOT FOUND(404)
GET http://localhost:3000/api/cursos/50

### POST /api/cursos/ crea un curso 
